name: Compiler le logiciel Windows
on:
  workflow_dispatch:
  push:
    branches: [main]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt pyinstaller
      - run: pyinstaller --onefile --windowed --name CroisementDocs --collect-data docx --collect-data pptx croisement.py
      - uses: actions/upload-artifact@v4
        with:
          name: CroisementDocs
          path: dist/CroisementDocs.exe
